# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
  'DevSupport'
]

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'GoogleSignIn'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
pod 'Firebase/AdMob'

target 'Nucleus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nucleus

  target 'Nucleus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  end

  target 'NucleusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'Nucleus-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nucleus-tvOS

  # target 'Nucleus-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

# end
