# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'GoogleSignIn'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'

target 'Nucleus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nucleus

  target 'Nucleus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NucleusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'Nucleus-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Nucleus-tvOS

  # target 'Nucleus-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

# end
